### ISSUE TITLE
TypeError: Object #<MQTTBrokerNode> has no method 'subscribe'

### ISSUE THREAD

**Issue by krauskopf** [Shirk/node-red-contrib-homegear-mqtt#4]
Node-RED version: v0.13.1
Node.js  version: v0.10.35

I'm trying to connect to my HM-CC-RT-DN but mqtt does not connect (though it is running). 

Node-Red error log shows the following error:

```
2 Feb 22:56:01 - [info] Starting flows
createConnection() is deprecated, use http://npm.im/mqtt-connection instead
2 Feb 22:56:01 - [info] [homegear-mqtt in:Arbeitszimmer] subscribing to topic "homegear/1234-5678-9abc/event/1/#"
2 Feb 22:56:01 - [error] [homegear-mqtt in:dc02169c.23fde8] TypeError: Object #<MQTTBrokerNode> has no method 'subscribe'
2 Feb 22:56:01 - [info] Started flows
```

**Comment by HealsCodes** [comment]
Looks like a change in nodered - I didn't have time to upgrade to 0.13 yet.
Thanks for reporting it - I'll try to provide a fix asap.

**Comment by HealsCodes** [comment]
@TheKrauskopf I gave it a try an 0.13.1 and sadly I can't reproduce your errors..
The MQTTBrokerNode didn't change API in the new release and should still work as before.
The only difference I see here is that I'm running node 5.0.0 instead of 0.10.1 but AFAIK that shouldn't matter:

```
Welcome to Node-RED
===================

3 Feb 18:02:17 - [info] Node-RED version: v0.13.1
3 Feb 18:02:17 - [info] Node.js  version: v5.0.0
3 Feb 18:02:17 - [info] Loading palette nodes
3 Feb 18:02:17 - [info] Settings file  : /xxxxxx/.node-red/settings.js
3 Feb 18:02:17 - [info] User directory : /xxxxxx/.node-red
3 Feb 18:02:17 - [info] Flows file : /xxxxxx/.node-red/flows_xxxxxxx.json
3 Feb 18:02:17 - [info] Server now running at http://127.0.0.1:1880/
3 Feb 18:02:17 - [info] Starting flows
3 Feb 18:02:17 - [info] [homegear-mqtt in:7521e62b.8ade18] subscribing to topic "homegear/1234-5678-9abc/event/1/#"
3 Feb 18:02:17 - [info] [homegear-mqtt in:7521e62b.8ade18] subscribing to topic "homegear/1234-5678-9abc/rpcResult"
3 Feb 18:02:17 - [info] Started flows
3 Feb 18:02:17 - [info] [mqtt-broker:41f5a240.be0a5c] Connection failed to broker: mqtt://127.0.0.1:1883
```

What's also strange is that I'm not seeing the deprecation warning (note: I did an upgrade, not a fresh install).

Could you share a minimal flow that produces the problem?

**Comment by krauskopf** [comment]
@Shirk At first, thanks for your help and for your fast response!

The flow is really simple. Just the homegear node and a debug message. Please note, that the mqtt input node connects successfully.

`[{"id":"9f20364e.60dfc8","type":"mqtt-broker","z":"","broker":"127.0.0.1","port":"1883","clientid":""},{"id":"7ccbb66c.833448","type":"debug","z":"a7c313d1.583cf","name":"","active":false,"console":"false","complete":"false","x":545,"y":327,"wires":[]},{"id":"dc02169c.23fde8","type":"homegear-mqtt in","z":"a7c313d1.583cf","broker":"9f20364e.60dfc8","homegearId":"1234-5678-9abc","peerId":1,"deviceType":"6:0","publishUpdates":true,"publishComplete":true,"name":"Arbeitszimmer","genName":"","x":259,"y":330,"wires":[["7ccbb66c.833448"]]},{"id":"2aa75693.d558aa","type":"mqtt in","z":"a7c313d1.583cf","name":"test","topic":"homegear/1234-5678-9abc/event/1/4/SET_TEMPERATURE","broker":"9f20364e.60dfc8","x":236,"y":394,"wires":[["567382ee.a98c7c"]]},{"id":"567382ee.a98c7c","type":"debug","z":"a7c313d1.583cf","name":"","active":true,"console":"false","complete":"false","x":554,"y":389,"wires":[]}]`

Looks like dependencies are mixed up!?

**Comment by krauskopf** [comment]
@Shirk Sorry, I've found the error. Was not a bug in node-red-contrib-homegear-mqtt!

A few week ago I've upgraded from a Node-RED version previous to 0.10.4, where the user data storage changed from install directory to $HOME/.node-red.
Unfortunately I've not only copied the files in /node/addon, but also the files in /nodes/core which also contained the old MQTTBrokerNode. Looks like the old one was then used, instead of the new one in the node-red install dir. I've deleted $HOME/.node-red/nodes/core and everything is working fine now!

Again, thanks for your help and please keep up the good work. You node is really helpfull!

**Comment by HealsCodes** [comment]
Glad it was only a dependency problem :smile:! 

I'm going to continue work on the convert_hg_xml branch in the combing weeks. If you like to give it a try I could offer some pre-release versions (and would be glad for the feedback).

That branch includes support for all families (homematic bidcos & wired as well as hue, insteon, sonos and MAX!) as well as using device descriptions directly created from what homegear uses so compatibility should be greatly improved.

**Comment by krauskopf** [comment]
Yeah, absolutely. I'd be happy to be beta tester. Although I do only have 3 HM-CC-RT-DN devices to test at the moment. But I could try to connect my 7 hue lamps also via homegear.

Drop me a line as soon as you have a pre-release!
